version: '3'
services:
  web:
    build: .
    # command: bundle exec ruby main.rb
    command: bundle exec puma
    environment:
      - "RACK_ENV=${RACK_ENV:-development}"
    ports:
      - "30001:9292"
    volumes:
      - .:/app
