version: '3'
services:
  app:
    build: .
    # command: bundle exec ruby main.rb
    command: bundle exec puma
    environment:
      - "RACK_ENV=${RACK_ENV:-development}"
    ports:
      - "9292:9292"
    volumes:
      - .:/app
